# Generated by Django 4.0.2 on 2023-01-04 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_intent_id', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Payment Intents',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SetupIntent',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('setup_intent_id', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Setup Intents',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_customer_id', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stripe Customers',
                'ordering': ('user__email',),
            },
        ),
        migrations.CreateModel(
            name='StripeProduct',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('stripe_product_id', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Stripe Products',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SubscribePlan',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(choices=[('CAD', 'CAD'), ('US', 'US')], default='CAD', max_length=10)),
                ('recurring_payment_value', models.FloatField()),
                ('recurring_interval', models.CharField(choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY'), ('YEARLY', 'YEARLY')], max_length=10)),
                ('stripe_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_plan', to='stripe_payment.stripeproduct')),
            ],
            options={
                'verbose_name_plural': 'Subscribe Plans',
                'ordering': ('stripe_product__name',),
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_subscription_id', models.CharField(max_length=256)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_customer', to='stripe_payment.stripecustomer')),
                ('subscribe_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscrber_plan', to='stripe_payment.subscribeplan')),
            ],
            options={
                'verbose_name_plural': 'Subscribers',
                'ordering': ('subscribe_plan__stripe_product__name', 'customer__user__email'),
            },
        ),
    ]
