# Generated by Django 4.0.2 on 2022-10-04 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stripe_payment', '0002_paymentintent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentintent',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Payment Intents'},
        ),
        migrations.RemoveField(
            model_name='paymentintent',
            name='user',
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
