# Generated by Django 4.0.2 on 2022-10-05 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0003_alter_paymentintent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeProduct',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('stripe_product_id', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Stripe Products',
                'ordering': ('name',),
            },
        ),
    ]
