# Generated by Django 4.0.2 on 2022-10-05 19:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0004_stripeproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribePlan',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_name', models.CharField(max_length=256)),
                ('reoccurring_payment_value', models.FloatField()),
                ('reocurring_period', models.CharField(choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY'), ('YEARLY', 'YEARLY')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Subscribe Plans',
                'ordering': ('plan_name',),
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_customer', to='stripe_payment.stripecustomer')),
                ('subscribe_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscrber_plan', to='stripe_payment.subscribeplan')),
            ],
            options={
                'verbose_name_plural': 'Subscribers',
                'ordering': ('subscribe_plan__plan_name', 'customer__user__email'),
            },
        ),
        migrations.DeleteModel(
            name='StripeProduct',
        ),
    ]
