# Generated by Django 4.0.2 on 2022-10-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0005_subscribeplan_subscriber_delete_stripeproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribeplan',
            name='currency',
            field=models.CharField(choices=[('CAD', 'CAD'), ('US', 'US')], default='CAD', max_length=10),
        ),
    ]
