# Generated by Django 4.0.2 on 2022-10-05 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0007_stripeproduct_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribeplan',
            options={'ordering': ('stripe_product__name',), 'verbose_name_plural': 'Subscribe Plans'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ('subscribe_plan__stripe_product__name', 'customer__user__email'), 'verbose_name_plural': 'Subscribers'},
        ),
        migrations.RemoveField(
            model_name='subscribeplan',
            name='plan_name',
        ),
        migrations.AddField(
            model_name='subscribeplan',
            name='stripe_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_plan', to='stripe_payment.stripeproduct'),
            preserve_default=False,
        ),
    ]
