# Generated by Django 4.0.2 on 2022-10-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0008_alter_subscribeplan_options_alter_subscriber_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='stripe_subscription_id',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
