# Generated by Django 4.0.2 on 2022-10-05 21:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0009_subscriber_stripe_subscription_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupIntent',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('setup_intent_id', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Setup Intents',
                'ordering': ('-created_at',),
            },
        ),
    ]
