# Generated by Django 4.0.2 on 2023-02-22 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='user',
        ),
        migrations.AddField(
            model_name='userevent',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_event', to='core.profile'),
        ),
    ]
