# Generated by Django 4.0.2 on 2023-02-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userevent_user_userevent_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='timezone',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
