# Pull official base image
FROM python:3.9.13-buster

# Assign the label for the developer (arbitrary)
LABEL Developer="Mohammad Mahdi Mohajer"

# Set environment variables. These are required for python images
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# IF useing selenium, uncomment the following part
# Also you need to add selenium>4.0.0,<=4.7.2 to the list of requiremets.txt
# --------------------********------------------------------
# RUN apt-get update -y
# RUN apt install chromium=89.0.4389.114-1~deb10u1 -y
# RUN apt install chromium-driver=89.0.4389.114-1~deb10u1 -y
# --------------------********------------------------------

# Set the working directory
WORKDIR /usr/src/app

# Update the pip package manager
RUN pip install --upgrade pip

# Copy requirements.txt and install all the required libraries
COPY ./requirements.txt .
RUN pip install -r requirements.txt
RUN pip install pytest pytest-django model_bakery pytest-watch isort flake8 autopep8

# Copy all the files from current folder to --->
# the working directory of the image
COPY . .

# Making the file docker-entrypoint.sh, wait-for executable
RUN chmod +x /usr/src/app/docker-entrypoint-dev.sh
RUN chmod +x /usr/src/app/docker-entrypoint-prod.sh
RUN chmod +x /usr/src/app/wait-for

# Open port 8000, default port for django:
EXPOSE 8000

# Create a user app that belongs to the group app
RUN useradd app

# Change the owner of current folder to the user app --->
# And set the user app as the current user
RUN chown -R app:app .
USER app